default_context:
  project_name: 'gateway'
  project_slug: 'gateway'
  domain_main: 'gateway.tips'
  domain_staging: 'stag.gateway.tips'
  docker_swarm_stack_name_main: 'gateway-tips'
  docker_swarm_stack_name_staging: 'stag-gateway-tips'
  secret_key: 'e35c1897f7a330b386a0d7e0'
  first_superuser: 'admin@gateway.tips'
  first_superuser_password: 'e35c1897f7a330b386a0d7e0'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.gateway.tips", "https://stag.gateway.tips", "https://gateway.tips", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@gateway.tips'
  postgres_password: 'e4528f4152ddedc8'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'gateway.tips'
  traefik_constraint_tag_staging: 'stag.gateway.tips'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin'
  sentry_dsn: 'https://59570860b0e04a839173c6b5ea2e88d5@sentry.roskomsvoboda.org/19'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
